[package]
name = "useless_efi"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4.29"
uefi = { version = "0.36.1", features = [
    "logger",
    "panic_handler",
    "alloc",
    "global_allocator",
] }
